routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Frontend
Route::resource('visitor', 'Frontend\VisitorController');

Route::get('/', 'HomeController@index')->name('home');

// Backend
Auth::routes();

Route::get('/backend','Backend\VisitorController@index');

app/Region.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Region extends Model
{
    protected $table    = 'regions';
    protected $fillable = ['name'];
}

app/Town.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Town extends Model
{
    protected $table    = 'towns';
    protected $fillable = ['name'];
}

app/Township.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Township extends Model
{
    protected $table    = 'townships';
    protected $fillable = ['name'];


    public function visitors()
    {
        return $this->hasMany('App\Visitor');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Visitor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Visitor extends Model
{
    protected $table    = 'visitors';
    protected $fillable = [
                            'name',
                            'email',
                            'phone_no',
                            'no',
                            'street',
                            'quarter',
                            'township_id',
                            'town_id',
                            'region_id',
                            'latitude',
                            'longitude' ];

    public function township()
    {
        return $this->belongsTo('App\Township');
    }

    public function town()
    {
        return $this->belongsTo('App\Town');
    }

    public function region()
    {
        return $this->belongsTo('App\Region');
    }

    public function getTownshipName($id)
    {
        return Township::where('id', $id)->select('name')->first();
    }

    public function getTownName($id)
    {
        return Town::where('id', $id)->select('name')->first();
    }

    public function getRegionName($id)
    {
        return Region::where('id', $id)->select('name')->first();
    }
}

app/Http/Controllers/Backend/VisitorController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Visitor;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class VisitorController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $visitors = Visitor::with('township','town','region')->get();

        return view('backend.visitors.index', compact('visitors'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Frontend/VisitorController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Town;
use App\Region;
use App\Visitor;
use App\Township;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\EloquentVisitor;
use App\Http\Requests\CreateVisitorRequest;
use App\Http\Requests\UpdateVisitorRequest;

class VisitorController extends Controller
{

    private $repo;
    private $dir;

    public function __construct()
    {
        $this->repo = new EloquentVisitor();
        $this->dir  = 'frontend.visitors.';
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $townships  = $this->getAddress()['townships'];
        $towns      = $this->getAddress()['towns'];
        $regions    = $this->getAddress()['regions'];

        return view($this->dir.'create',compact('townships','towns','regions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateVisitorRequest $request)
    {
        $request = $this->saveAddress($request->all());

        $visitor = new Visitor();

        $this->repo->createVisitor($visitor, $request);

        return redirect('/visitor')->with('status', 'Successfully Created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $townships  = $this->getAddress()['townships'];
        $towns      = $this->getAddress()['towns'];
        $regions    = $this->getAddress()['regions'];

        $visitor = Visitor::findOrFail($id);

        return view($this->dir.'edit',compact('visitor', 'townships', 'towns','regions'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateVisitorRequest $request, $id)
    {
        $request = $this->saveAddress($request->all());

        $visitor = Visitor::findOrFail($id);

        $this->repo->createVisitor($visitor, $request);

        return redirect('/backend')->with('status', 'Successfully Updated!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $visitor = Visitor::findOrFail($id);

        $this->repo->deleteVisitor($visitor);

        return redirect('/backend')->with('status', 'Successfully Deleted!');
    }


    private function getAddress()
    {
        $townships  = new EloquentVisitor(Township::all());
        $townships  = $townships->getTownship();

        $towns      = new EloquentVisitor(Town::all());
        $towns      = $towns->getTown();

        $regions    = new EloquentVisitor(Region::all());
        $regions    = $regions->getRegion();

        return ['townships' => $townships, 'towns' => $towns, 'regions' => $regions];
    }

    private function saveAddress($request)
    {
        if (!is_numeric($request['township']))
        {
           $request['township'] = $this->repo->createTownship($request['township']);
        }
        else
        {
            $request['township'] = $request['township'];
        }

        if (!is_numeric($request['town']))
        {
            $request['town'] = $this->repo->createTown($request['town']);
        }

        return $request;
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/backend/visitors/index.blade.php
@extends('layouts.app')
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Visitors</div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert" id="success-alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <strong>{{ session('status') }}</strong>
                            </div>
                        @endif
                        <table class="table table-responsive table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Phone</th>
                                <th>Address</th>
                                <th>Position [lat, long]</th>
                                <th></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($visitors as $visitor)
                                <tr>
                                    <td>{{ $visitor->id }}.</td>
                                    <td>{{ $visitor->name }}</td>
                                    <td>{{ $visitor->email }}</td>
                                    <td>{{ $visitor->phone_no }}</td>
                                    <td>
                                        {{ $visitor->no .', '. $visitor->street .', '. $visitor->quarter.', ' }}
                                        {{ $visitor->township->name .', '. $visitor->town->name .', '. $visitor->region->name}}
                                    </td>
                                    <td>
                                        {{ $visitor->latitude .', '. $visitor->longitude }}
                                    </td>
                                    <td>
                                        <a class="btn btn-primary" href="{{ route('visitor.edit', $visitor->id) }}">edit</a>
                                    </td>
                                    <td>
                                        {{ Form::open(['method' => 'DELETE','data-confirm' => 'delete?', 'route' => array('visitor.destroy', $visitor->id)]) }}
                                            <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure ?')">delete</button>
                                        {{ Form::close() }}
                                    </td>
                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/frontend/layouts/app.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{env('title')}}</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />

    {{-- Google Map--}}
    <link rel="stylesheet" type="text/css" href="{{ asset('google-map/css/demo.css') }}"/>

    <!-- Dependencies: JQuery and GMaps API should be loaded first -->
    <script src="{{ asset('google-map/js/jquery-2.1.1.min.js') }}"></script>
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyAOSibRMpAGVAFkTvFxGKVi44A-S14FVas"></script>

    <!-- CSS and JS for our code -->
    <link rel="stylesheet" type="text/css" href="{{ asset('google-map/css/jquery-gmaps-latlon-picker.css') }}"/>
    <script src="{{ asset('google-map/js/jquery-gmaps-latlon-picker.js') }}"></script>

</head>
<body>
<div class="container">
    <h1 class="text-center">Visitor Information</h1>
</div>

@if (session('status'))
    <div class="alert alert-success alert-dismissible fade show" role="alert" id="success-alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>{{ session('status') }}</strong>
    </div>
@endif

<div class="container">
    @yield('content')
</div>

</body>
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<script>
    $(document).ready(function() {
        $(".select2-township").select2({
            tags: true,
            createTag: function (params) {
                return {
                    id: params.term,
                    text: params.term,
                    newOption: true
                }
            }
        });
        $(".select2-town").select2({
            tags: true,
            createTag: function (params) {
                return {
                    id: params.term,
                    text: params.term,
                    newOption: true
                }
            }
        });
        $(".select2-region").select2({
        });
    });

</script>
</html>

resources/views/frontend/visitors/create.blade.php
@extends('frontend.layouts.app')
@section('content')
    {{ Form::open(array('name' => 'visitor')) }}
    <div class="form-group row  {{ $errors->has('name') ? ' error' : '' }}">
        <label for="name" class="col-2 col-form-label">Name</label>
        <div class="col-10">
            <input class="form-control" type="text" name="name" value="{{ old('name') }}">
            <small class="text-danger">{{ $errors->first('name') }}</small>
        </div>
    </div>
    <div class="form-group row {{ $errors->has('email') ? ' error' : '' }}">
        <label for="email" class="col-2 col-form-label">Email</label>
        <div class="col-10">
            <input class="form-control" type="email" name="email" value="{{ old('email') }}">
            <small class="text-danger">{{ $errors->first('email') }}</small>
        </div>
    </div>
    <div class="form-group row {{ $errors->has('phone_no') ? ' error' : '' }}">
        <label for="phone_no" class="col-2 col-form-label">Phone Number</label>
        <div class="col-10">
            <input class="form-control" type="tel" name="phone_no" value="{{ old('phone_no') }}">
            <small class="text-danger">{{ $errors->first('phone_no') }}</small>
        </div>
    </div>
    <div class="form-group row {{ $errors->has('no') ? ' error' : '' }}">
        <label for="no" class="col-2 col-form-label">No.</label>
        <div class="col-10">
            <input class="form-control" type="text" name="no" value="{{ old('no') }}">
            <small class="text-danger">{{ $errors->first('no') }}</small>
        </div>
    </div>
    <div class="form-group row {{ $errors->has('street') ? ' error' : '' }}">
        <label for="street" class="col-2 col-form-label">Street</label>
        <div class="col-10">
            <input class="form-control" type="text" name="street" value="{{ old('street') }}">
            <small class="text-danger">{{ $errors->first('street') }}</small>
        </div>
    </div>
    <div class="form-group row {{ $errors->has('quarter') ? ' error' : '' }}">
        <label for="quarter" class="col-2 col-form-label">Quarter</label>
        <div class="col-10">
            <input class="form-control" type="text" name="quarter" value="{{ old('quarter') }}">
            <small class="text-danger">{{ $errors->first('quarter') }}</small>
        </div>
    </div>
    <div class="form-group row {{ $errors->has('township') ? ' error' : '' }}">
        <label for="example-text-input" class="col-2 col-form-label">Township</label>
        <div class="col-10">
            <select class="select2-township form-control" name="township">
                @foreach($townships as $township)
                    <option value="{{ $township->id }}">{{ $township->name }}</option>
                @endforeach
            </select>
            <small class="text-danger">{{ $errors->first('township') }}</small>
        </div>
    </div>
    <div class="form-group row {{ $errors->has('town') ? ' error' : '' }}">
        <label for="example-text-input" class="col-2 col-form-label">Town</label>
        <div class="col-10">
            <select class="select2-town form-control" name="town">
                @foreach($towns as $town)
                    <option value="{{ $town->id }}">{{ $town->name }}</option>
                @endforeach
            </select>
            <small class="text-danger">{{ $errors->first('town') }}</small>
        </div>
    </div>
    <div class="form-group row {{ $errors->has('region') ? ' error' : '' }}">
        <label for="example-text-input" class="col-2 col-form-label">Region</label>
        <div class="col-10">
            <select class="select2-region form-control" name="region">
                @foreach($regions as $region)
                    <option value="{{ $region->id }}">{{ $region->name }}</option>
                @endforeach
            </select>
            <small class="text-danger">{{ $errors->first('region') }}</small>
        </div>
    </div>
    <div class="form-group offset-2">
        <fieldset class="gllpLatlonPicker">
            <div class="form-inline form-group">
                <input type="text" class="gllpSearchField form-control col-md-4">
                &nbsp; <input type="button" class="gllpSearchButton btn btn-default" value=" search">
            </div>
            <div class="gllpMap">Google Maps</div>
            <input type="hidden" class="gllpLatitude" value="20" name="latitude"/>
            <input type="hidden" class="gllpLongitude" value="20" name="longitude"/>
            <input type="hidden" class="gllpZoom" value="3"/>
        </fieldset>
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-success btn-lg">Submit</button>
    </div>
    {{ Form::close() }}
@endsection

resources/views/frontend/visitors/edit.blade.php
@extends('frontend.layouts.app')
@section('content')
    {{ Form::model($visitor, array('route' => ['visitor.update',$visitor->id], 'method' => 'PUT')) }}
    <input type="hidden" name="id" value="{{ $visitor->id }}">
    <div class="form-group row {{ $errors->has('name') ? ' error' : '' }}">
        <label for="example-text-input" class="col-2 col-form-label">Name</label>
        <div class="col-10">
            <input class="form-control" type="text" name="name" value="{{ old('name', $visitor->name) }}">
            <small class="text-danger">{{ $errors->first('name') }}</small>
        </div>
    </div>
    <div class="form-group row {{ $errors->has('email') ? ' error' : '' }}">
        <label for="example-email-input" class="col-2 col-form-label">Email</label>
        <div class="col-10">
            <input class="form-control" type="email" name="email" value="{{ old('email', $visitor->email) }}">
            <small class="text-danger">{{ $errors->first('email') }}</small>
        </div>
    </div>
    <div class="form-group row {{ $errors->has('phone_no') ? ' error' : '' }}">
        <label for="example-tel-input" class="col-2 col-form-label">Phone Number</label>
        <div class="col-10">
            <input class="form-control" type="tel" name="phone_no" value="{{ old('phone_no', $visitor->phone_no) }}">
            <small class="text-danger">{{ $errors->first('phone_no') }}</small>
        </div>
    </div>
    <div class="form-group row {{ $errors->has('no') ? ' error' : '' }}">
        <label for="example-text-input" class="col-2 col-form-label">No.</label>
        <div class="col-10">
            <input class="form-control" type="text" name="no" value="{{ old('no', $visitor->no) }}">
            <small class="text-danger">{{ $errors->first('no') }}</small>
        </div>
    </div>
    <div class="form-group row {{ $errors->has('street') ? ' error' : '' }}">
        <label for="example-text-input" class="col-2 col-form-label">Street</label>
        <div class="col-10">
            <input class="form-control" type="text" name="street" value="{{ old('street', $visitor->street) }}">
            <small class="text-danger">{{ $errors->first('street') }}</small>
        </div>
    </div>
    <div class="form-group row {{ $errors->has('quarter') ? ' error' : '' }}">
        <label for="example-text-input" class="col-2 col-form-label">Quarter</label>
        <div class="col-10">
            <input class="form-control" type="text" name="quarter" value="{{ old('quarter', $visitor->quarter) }}">
            <small class="text-danger">{{ $errors->first('quarter') }}</small>
        </div>
    </div>
    <div class="form-group row {{ $errors->has('township') ? ' error' : '' }}">
        <label for="example-text-input" class="col-2 col-form-label">Township</label>
        <div class="col-10">
            <select class="select2-township form-control" name="township">
                @foreach($townships as $township)
                    <option value="{{ $township->id }}" {{ old('township', $visitor->township_id) == $township->id ? "selected":"" }}>{{ $township->name }}</option>
                @endforeach
            </select>
            <small class="text-danger">{{ $errors->first('township') }}</small>
        </div>
    </div>
    <div class="form-group row {{ $errors->has('town') ? ' error' : '' }}">
        <label for="example-text-input" class="col-2 col-form-label">Town</label>
        <div class="col-10">
            <select class="select2-town form-control" name="town">
                @foreach($towns as $town)
                    <option value="{{ $town->id }}" {{ old('town', $visitor->town_id) == $town->id ? "selected":"" }}>{{ $town->name }}</option>
                @endforeach
            </select>
            <small class="text-danger">{{ $errors->first('town') }}</small>
        </div>
    </div>
    <div class="form-group row {{ $errors->has('region') ? ' error' : '' }}">
        <label for="example-text-input" class="col-2 col-form-label">Region</label>
        <div class="col-10">
            <select class="select2-region form-control" name="region">
                @foreach($regions as $region)
                    <option value="{{ $region->id }}" {{ old('region', $visitor->region_id) == $region->id ? "selected":"" }}>{{ $region->name }}</option>
                @endforeach
            </select>
            <small class="text-danger">{{ $errors->first('region') }}</small>
        </div>
    </div>
    <div class="form-group col md-10 offset-2">
        <fieldset class="gllpLatlonPicker">
            <div class="form-inline form-group">
                <input type="text" class="gllpSearchField form-control col-md-4">
                &nbsp; <input type="button" class="gllpSearchButton btn btn-default" value=" search">
            </div>
            <div class="gllpMap">Google Maps</div>
            <input type="hidden" class="gllpLatitude" value="{{ $visitor->latitude }}" name="latitude"/>
            <input type="hidden" class="gllpLongitude" value="{{ $visitor->longitude }}" name="longitude"/>
            <input type="hidden" class="gllpZoom" value="15"/>
        </fieldset>
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-success btn-lg">Submit</button>
    </div>
    {{ Form::close() }}
@endsection

resources/views/home.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <style>
        html, body {
            background-color: #fff;
            color: #636b6f;
            font-family: 'Raleway', sans-serif;
            font-weight: 100;
            height: 100vh;
            margin: 0;
        }

        .full-height {
            height: 100vh;
        }

        .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
        }

        .position-ref {
            position: relative;
        }

        .top-right {
            position: absolute;
            right: 10px;
            top: 18px;
        }

        .content {
            text-align: center;
        }

        .title {
            font-size: 84px;
        }

        .links > a {
            color: #636b6f;
            padding: 0 25px;
            font-size: 12px;
            font-weight: 600;
            letter-spacing: .1rem;
            text-decoration: none;
            text-transform: uppercase;
        }

        .m-b-md {
            margin-bottom: 30px;
        }
    </style>
</head>
<body>
<div class="flex-center position-ref full-height">

    <div class="content">
        <div class="title m-b-md">
            za information technology
        </div>

        <div class="links">
            <a href="{{ URL::to('/visitor') }}">Register ...</a>
        </div>
    </div>
</div>
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }}
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>